/*
* AUTOGENERATED FILE
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))=
        "****************"  // placeholder for beggining
        "20260603T221320"   // DateTime using ISO-8601 format
        " "                 // alignment
        "fe4f403e"          // STLIB commit
        "--------"          // ADJ commit
        "3175efc7"          // Board commit
        // the '=' is used for unparsing
        ;
}